### PR TITLE
[actions] use ljharb/actions/node/matrix

### PR DESCRIPTION
**Pull request by ljharb**
(into #1)

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
LGTM ! BTW that cool action

**Review by JakobJingleheimer — APPROVED** [review]
w00t! Thanks for this 🙏

**Comment by JakobJingleheimer** [comment]
@ljharb something in here causes CI to fail on globs (ex https://github.com/nodejs/userland-migrations/actions/runs/12068897635/job/33654997438)

**Comment by ljharb** [comment]
@JakobJingleheimer rather than reverting, it might be more helpful to print out `node --version` in the tests, to make sure it's using the right one? node itself is failing on the options, not the globs, from what i can see.

**Comment by richardlau** [comment]
https://github.com/nodejs/userland-migrations/actions/runs/12068897635/job/33654997438#step:3:9 says it installed Node.js 20.18.1

**Comment by JakobJingleheimer** [comment]
> @JakobJingleheimer rather than reverting, it might be more helpful to print out `node --version` in the tests, to make sure it's using the right one? node itself is failing on the options, not the globs, from what i can see.

Ah, yes. I reverted because I think this is super cool but non-blocking. Since the parent PR is otherwise ready to go, I think we can figure this out and then as a subsequent enhancement. And the other landed, I think this will be easier to test 🙂

**Pull request merged**
